# Filter và xoá VQA yes-no cho 2 qtype

Notebook này sẽ:
1. Đọc bảng `vqa` từ Supabase
2. Lọc các dòng có `qtype` thuộc `allergen_restrictions` hoặc `dietary_restrictions`
3. Xác định câu hỏi yes-no theo định nghĩa mới: **cả 4 lựa chọn đều chứa `Có, ` hoặc `Không, `**
4. Preview các dòng sẽ bị xoá
5. Backup các dòng đó ra CSV
6. Xoá khỏi Supabase theo `vqa_id`

> Mặc định notebook chạy ở chế độ **an toàn**: chỉ preview và backup. Chỉ khi bạn đặt `APPLY_DELETE = True` thì mới xoá thật.

In [1]:
from supabase import create_client
import os
from pathlib import Path
import pandas as pd

# Điền trực tiếp hoặc lấy từ env
SUPABASE_URL = "https://cvdoasxazyruytejluvv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2ZG9hc3hhenlydXl0ZWpsdXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMTM3NzEsImV4cCI6MjA4ODc4OTc3MX0.jWnKQXoKlXOJXua-Q0Z5Dcqq5kLhXD7rmIA2w7FogSg"

client = create_client(SUPABASE_URL, SUPABASE_KEY)

PAGE_SIZE = 1000
DELETE_BATCH_SIZE = 500
TARGET_QTYPES = {"allergen_restrictions", "dietary_restrictions", "cooking_technique", "dish_classification", "flavor_profile", "food_pairings", "ingredients", "ingredient_category"}
OUTPUT_DIR = Path("data/filter_yes_no_cleanup")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Connected to Supabase")
print("Output dir:", OUTPUT_DIR.resolve())

Connected to Supabase
Output dir: D:\Code\HCMUS\NNHTK\ViFoodKG\notebooks\data\filter_yes_no_cleanup

In [2]:
def fetch_all_vqa(page_size=1000):
    all_rows = []
    page = 0
    while True:
        resp = (
            client.table("vqa")
            .select(
                "vqa_id, image_id, qtype, question, choice_a, choice_b, choice_c, choice_d, answer, rationale, triples_used, is_checked, is_drop"
            )
            .order("vqa_id")
            .range(page * page_size, (page + 1) * page_size - 1)
            .execute()
        )
        rows = resp.data or []
        if not rows:
            break
        all_rows.extend(rows)
        print(f"Fetched page {page}: {len(rows)} rows")
        if len(rows) < page_size:
            break
        page += 1
    return all_rows

def normalize_text(text):
    return str(text or "").strip()

def contains_yes_no_token(text: str) -> bool:
    t = normalize_text(text).lower()
    return ("có, " in t) or ("không, " in t)

def is_yes_no_row(row) -> bool:
    choices = [
        normalize_text(row.get("choice_a")),
        normalize_text(row.get("choice_b")),
        normalize_text(row.get("choice_c")),
        normalize_text(row.get("choice_d")),
    ]
    return all(contains_yes_no_token(choice) for choice in choices)

def chunked(seq, size):
    for i in range(0, len(seq), size):
        yield seq[i:i + size]

## 1) Preview các dòng sẽ bị xoá

In [3]:
rows = fetch_all_vqa(PAGE_SIZE)
df = pd.DataFrame(rows)

target_df = df[df["qtype"].isin(TARGET_QTYPES)].copy()
delete_df = target_df[target_df.apply(is_yes_no_row, axis=1)].copy()

print("Tổng số dòng trong vqa:", len(df))
print("Tổng số dòng thuộc 2 qtype mục tiêu:", len(target_df))
print("Số dòng yes-no sẽ bị xoá:", len(delete_df))

display(
    delete_df.groupby("qtype")
    .size()
    .reset_index(name="delete_count")
    .sort_values("delete_count", ascending=False)
    .reset_index(drop=True)
)

display(
    delete_df[
        ["vqa_id", "image_id", "qtype", "question", "choice_a", "choice_b", "choice_c", "choice_d"]
    ].head(30)
)

Fetched page 0: 1000 rows
Fetched page 1: 1000 rows
Fetched page 2: 1000 rows
Fetched page 3: 1000 rows
Fetched page 4: 103 rows
Tổng số dòng trong vqa: 4103
Tổng số dòng thuộc 2 qtype mục tiêu: 3921
Số dòng yes-no sẽ bị xoá: 0

Empty DataFrame
Columns: [qtype, delete_count]
Index: []

Empty DataFrame
Columns: [vqa_id, image_id, qtype, question, choice_a, choice_b, choice_c, choice_d]
Index: []

## 2) Backup các dòng sắp xoá ra CSV

In [4]:
backup_csv = OUTPUT_DIR / "vqa_yes_no_rows_to_delete.csv"
delete_df.to_csv(backup_csv, index=False, encoding="utf-8-sig")
print("Saved backup CSV:", backup_csv.resolve())

Saved backup CSV: D:\Code\HCMUS\NNHTK\ViFoodKG\notebooks\data\filter_yes_no_cleanup\vqa_yes_no_rows_to_delete.csv

## 3) Xoá khỏi Supabase

Đặt `APPLY_DELETE = True` rồi chạy cell dưới nếu bạn muốn xoá thật.

In [5]:
APPLY_DELETE = True

vqa_ids_to_delete = delete_df["vqa_id"].dropna().astype(int).tolist()
print("Rows prepared for deletion:", len(vqa_ids_to_delete))

if not APPLY_DELETE:
    print("Dry run only. Chưa xoá gì cả. Đổi APPLY_DELETE = True để xoá thật.")
else:
    deleted = 0
    for batch in chunked(vqa_ids_to_delete, DELETE_BATCH_SIZE):
        (
            client.table("vqa")
            .delete()
            .in_("vqa_id", batch)
            .execute()
        )
        deleted += len(batch)
        print(f"Deleted {deleted}/{len(vqa_ids_to_delete)}")
    print("Done.")

Rows prepared for deletion: 441
Deleted 441/441
Done.

## 4) Kiểm tra lại sau khi xoá

In [6]:
rows_after = fetch_all_vqa(PAGE_SIZE)
df_after = pd.DataFrame(rows_after)
target_after = df_after[df_after["qtype"].isin(TARGET_QTYPES)].copy()
delete_after = target_after[target_after.apply(is_yes_no_row, axis=1)].copy()

print("Số dòng yes-no còn lại trong 2 qtype mục tiêu:", len(delete_after))
display(
    delete_after.groupby("qtype")
    .size()
    .reset_index(name="remaining_count")
    .sort_values("remaining_count", ascending=False)
    .reset_index(drop=True)
)

Fetched page 0: 1000 rows
Fetched page 1: 1000 rows
Fetched page 2: 1000 rows
Fetched page 3: 606 rows
Số dòng yes-no còn lại trong 2 qtype mục tiêu: 0

Empty DataFrame
Columns: [qtype, remaining_count]
Index: []